language: node_js
install:
- npm install
script:
- gulp
deploy:
  provider: firebase
  token:
    secure: gQH3wbka/TWW+dpxrozP3w4haY3ei2DlaqYoro/uCRByyhzp10H31OF4NlDWmJ3+eXjPxvwi8oTKNCcknyA7juYdL/RbaGB2lcx8JOgbnOfleT+8QOwZO7Pwj1oQLKsxf0FRZO6eeHOHyDdNi8uhPRqdjiyLfWUNTDA9APtW/VDo3ZqGqRYIzvpX0SgqEWPMxCFz+uJqcnuPq3DCnQ5xRwOW73ai8sYGvbIfJBDlnFkjaGi5SUeLaJXyy3dMTETTffDEmLmrJqoOXtGV5yf0nDkkaEUZhTpui+68wnTdICI/D0UODWT8di4I5wbghxCdpDqoVhlvXrbhFbExSajyoVdZrKImnPGqb8LkG6S6RqN655mbuqf4pbo+aQNSgFzlfrXDDZ2yskpnsxWWyR4Eq6UUFbTa2yoeDHjFZ/bgzoXFhzBWLZjSsjfLNGTyzNzSqjRYeT9E3HFCfTEGxu0jee+HPBMt1F8XjAh3uTMwpScceu7xdQHBjrTdltLoSMHXafz9r/4DOfEXwR5yYsUXasDEE5jGYaSOcYassdGzSPby2nbkmKe+m/QO4FfIag6juIhxvktSwprD2Eg3pRJA2QcLOpl5Kz36yyRzQVnNctS504UR82wLYjvaX/Jty6vmXp6jt7VQJZ1WMXsxSdB5Cv3ALXd/eMIYX0bScLRbW+0=
