language: node_js
node_js:
- "node"
install:
- npm install
script:
- npm run generate
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: bd2KigtEuZnVj4nrH9yYTjOgUpxeQCJ6cMZtAV4XhRJq/xestoy75E3sjR4KH1R68B7JnMqsAHHexcfOH6QsyAkdHx19YnilPkUUDUllR4g9mKwpo77s3XU68PZf8qQLHMkYnWvFOqswxYBEaoVfJLdKRSloguhz2qBhfftwwYLLzzkAlu/JV1RbUs3TDSPsgnzV9CWOMxufwnRCoFDqr3EX/g7qZ2JFBfdSktyMK1OGQZER7sPS0JIhItiFRjQXUt3/sTQZEPoiX2IMkHxy+Iz/BVo9FZ5okG9kFORH2wTFLxASk1jc9AMaqGxJDDaS7Z4EmnTAPwk2l0HNEwD5XpB9rvNWgcNhDouQ/70egNFMAw01/4pD/KEmJ81AfIghjDOb08s9QFTKdkSYBg38NuqK10ANqpxaQVztpM+RLENAafr8XZPnZlR+Kk+5b1qaTgEwxdXV1WJesAbQC9Rx3w3bqprQKjim+J4gddXl1JXS0SJMiogtq3huka04FOCGcyy1tsPzAG99orLuVqzK4bzYqVG6W+PnP5JrrB6km/tLK/Gq7H0xCNhYDH0aKKn8m/9fxsf8s9ZUlkK5T3sEi7MaAC3y0UP0/5JMfCetoZiAPFITg2Ow7kRakSq91JleFAmZCPgsFsyKEhqBWzD7/o8HoKEP9VdtXrTztjIKLk4=
